@echo off
rem  Double-click this to apply the settings in this folder.
rem
rem  Generated by cs2-config. Everything is in this one file: the PowerShell below
rem  the marker is plain text, and cmd stops reading at the exit above it.

setlocal
title CS2 config

rem  Cyrillic needs a console codepage that can render it; a stock Russian console is 866.
rem  Switch to UTF-8 and put the old one back on the way out, so running this from an
rem  existing terminal leaves no trace.
set "CP="
for /f "tokens=2 delims=:" %%c in ('chcp') do set "CP=%%c"
chcp 65001 >nul

set "PS1=%TEMP%\apply-config.ps1"
if exist "%PS1%" del "%PS1%"

rem  Via an environment variable, so an apostrophe in the path cannot break the string.
set "SELF=%~f0"
powershell -NoProfile -Command "$m='::'+'CFG::'; $t=[IO.File]::ReadAllText($env:SELF,[Text.Encoding]::UTF8); $i=$t.LastIndexOf($m); if($i -lt 0){exit 1}; [IO.File]::WriteAllText($env:TEMP+'\apply-config.ps1', $t.Substring($i+$m.Length), (New-Object Text.UTF8Encoding($true)))"
if not exist "%PS1%" goto broken

rem  Switches go straight through. With none the script shows its own menu: that lives on
rem  the PowerShell side, which already knows the display language, while cmd would need a
rem  second way to work it out.
powershell -NoProfile -ExecutionPolicy Bypass -File "%PS1%" %*

rem  Leave nothing behind on a machine you borrowed.
if exist "%PS1%" del "%PS1%"
echo.
pause
call :restorecp
exit /b 0

:broken
rem  Both languages at once, no detection. This runs when the file itself is damaged,
rem  which is the worst possible place for one more thing that can go wrong.
echo.
echo Could not unpack the script from this file.
echo Re-download it: some editors and chat apps corrupt .cmd files.
echo.
echo If PowerShell is blocked here, copy cfg\*.cfg into the game folder by hand,
echo or paste apply-config-using-console.txt into the CS2 console instead.
echo.
echo Не удалось распаковать скрипт из этого файла.
echo Скачай его заново: некоторые редакторы и мессенджеры портят .cmd.
echo.
echo Если тут закрыт PowerShell, скопируй cfg\*.cfg в папку игры вручную
echo или вставь содержимое apply-config-using-console.txt в консоль CS2.
echo.
pause
call :restorecp
exit /b 1

:restorecp
if defined CP chcp %CP% >nul
goto :eof

::CFG::<#
    CS2 settings pack. SELF-CONTAINED - every config is embedded below, so this one
    file is all you need on another PC. No git, no ZIP, no internet.

    Double-click apply-config.cmd and pick from the menu, or pass a switch to it
    and the menu is skipped:

      apply-config.cmd            configs only
      apply-config.cmd -Video     also apply resolution and quality
      apply-config.cmd -Convars   also restore sensitivity and binds (if Steam Cloud failed)
      apply-config.cmd -Check     show what differs, write nothing
      apply-config.cmd -Undo      put this PC back the way you found it

    GENERATED FILE. Rebuild it with update-config.cmd instead of editing it.
#>
param(
    [switch]$Video,
    [switch]$Convars,
    [switch]$Check,
    [switch]$Undo
)

$ErrorActionPreference = 'Stop'
$BackupRoot = Join-Path $env:TEMP 'cs2-config-apply-backup'
$Backup     = Join-Path $BackupRoot (Get-Date -Format 'yyyyMMdd-HHmmss')

# The Windows display language decides, and nothing else. Keyboard layouts are not
# consulted. Every message carries both languages at the call site; passing only English
# means "same in both", which is what you want for paths and file names.
$Lang = 'en'
try {
    if ((Get-UICulture).TwoLetterISOLanguageName -eq 'ru') { $Lang = 'ru' }
} catch { }

function L($en, $ru) {
    if ($Lang -eq 'ru' -and $ru) { return $ru }
    return $en
}
function Info($en, $ru) { Write-Host "     $(L $en $ru)" }
function Ok  ($en, $ru) { Write-Host "OK   $(L $en $ru)" -ForegroundColor Green }
function Warn($en, $ru) { Write-Host "WARN $(L $en $ru)" -ForegroundColor Yellow }
function Die ($en, $ru) { Write-Host "FAIL $(L $en $ru)" -ForegroundColor Red; exit 1 }

# Status words sit in a fixed column, and the Russian ones are longer. Pad, do not count.
function Mark($en, $ru) { return (L $en $ru).PadRight(11) }

# Windows does not care how a path is spelled, but whoever reads the output does. Steam
# writes SteamPath into the registry all lower case and with forward slashes, like
# c:/program files (x86)/steam. The slashes are a substitution; how the folders are really
# spelled only the filesystem knows, so every segment is looked up in its parent.
function Get-TruePath($path) {
    $dir = New-Object IO.DirectoryInfo $path
    if (-not $dir.Exists) { return $path }
    $parts = New-Object System.Collections.Generic.List[string]
    while ($dir.Parent) {
        $hit = $dir.Parent.GetDirectories($dir.Name)
        if ($hit.Count -lt 1) { return $path }
        $parts.Insert(0, $hit[0].Name)
        $dir = $dir.Parent
    }
    # Only a drive letter is worth upper-casing. A UNC root is spelled by its server.
    $root = $dir.Name.TrimEnd('\')
    if ($root -match '^[a-z]:$') { $root = $root.ToUpper() }
    if ($parts.Count -eq 0) { return "$root\" }
    return $root + '\' + ($parts -join '\')
}

function Get-SteamPath {
    foreach ($k in @('HKCU:\Software\Valve\Steam',
                     'HKLM:\SOFTWARE\WOW6432Node\Valve\Steam',
                     'HKLM:\SOFTWARE\Valve\Steam')) {
        if (Test-Path $k) {
            $p = Get-ItemProperty $k
            $raw = $p.SteamPath
            if (-not $raw) { $raw = $p.InstallPath }
            if ($raw) { return Get-TruePath (($raw -replace '/', '\').TrimEnd('\')) }
        }
    }
    return $null
}

function Get-CS2CfgPath($steam) {
    $roots = New-Object System.Collections.Generic.List[string]
    $roots.Add($steam)
    $vdf = Join-Path $steam 'steamapps\libraryfolders.vdf'
    if (Test-Path $vdf) {
        foreach ($line in Get-Content $vdf) {
            if ($line -match '"path"\s+"(.+?)"') { $roots.Add(($matches[1] -replace '\\\\', '\')) }
        }
    }
    foreach ($r in $roots) {
        $p = Join-Path $r 'steamapps\common\Counter-Strike Global Offensive\game\csgo\cfg'
        if (Test-Path $p) { return Get-TruePath $p }
    }
    return $null
}

function Get-UserCfgPath($steam) {
    if (Test-Path 'HKCU:\Software\Valve\Steam\ActiveProcess') {
        $id = (Get-ItemProperty 'HKCU:\Software\Valve\Steam\ActiveProcess').ActiveUser
        if ($id -and $id -ne 0) {
            $p = Join-Path $steam "userdata\$id\730\local\cfg"
            if (Test-Path $p) { return $p }
        }
    }
    $ud = Join-Path $steam 'userdata'
    if (-not (Test-Path $ud)) { return $null }
    $best = Get-ChildItem $ud -Directory -ErrorAction SilentlyContinue |
            Where-Object { Test-Path (Join-Path $_.FullName '730\local\cfg') } |
            Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if ($best) { return (Join-Path $best.FullName '730\local\cfg') }
    return $null
}

$UTF8 = New-Object System.Text.UTF8Encoding($false)

function Normalize($text) { return ($text -replace "`r`n", "`n").TrimEnd("`n", " ", "`t") }

function Compare-Payload($map, $destDir, $label) {
    if (-not $destDir) { return }
    foreach ($name in $map.Keys) {
        $dest = Join-Path $destDir $name
        if (-not (Test-Path $dest)) { Write-Host "     $(Mark 'MISSING' 'НЕТ ВОВСЕ')$label/$name" -ForegroundColor Yellow }
        elseif ((Normalize ([IO.File]::ReadAllText($dest))) -eq (Normalize $map[$name])) {
            Info "$(Mark 'same' 'совпадает')$label/$name"
        }
        else { Write-Host "     $(Mark 'DIFFERENT' 'ОТЛИЧАЕТСЯ')$label/$name" -ForegroundColor Yellow }
    }
}

function Write-Payload($map, $destDir, $tag) {
    $bdir  = Join-Path $Backup $tag
    $added = New-Object System.Collections.Generic.List[string]
    foreach ($name in $map.Keys) {
        $dest = Join-Path $destDir $name
        if (Test-Path $dest) {
            New-Item -ItemType Directory -Force $bdir | Out-Null
            Copy-Item $dest $bdir -Force
        } else {
            # Nothing to back up: remember it so -Undo can delete it again.
            $added.Add($name)
        }
        [IO.File]::WriteAllText($dest, ($map[$name] -replace "`r?`n", "`r`n") + "`r`n", $UTF8)
        Info $name
    }
    if ($added.Count -gt 0) {
        New-Item -ItemType Directory -Force $bdir | Out-Null
        [IO.File]::WriteAllLines((Join-Path $bdir '_added.txt'), $added)
    }
}
$GameCfg = [ordered]@{}
$GameCfg['autoexec.cfg'] = @'
// CS2 runs this file automatically on startup.
// It stays tiny on purpose - it just chains to the real config,
// so there is only one place to edit.

exec oceanvievv

// Force the settings above to be written to disk so they survive
// the next time CS2 saves its own config.
host_writeconfig

// ---- added by cs2-config ----
exec crosshair
host_writeconfig
'@
$GameCfg['crosshair.cfg'] = @'
// Crosshair, read from your CS2 settings by cs2-config.
// Applying this needs no share code.

cl_crosshair_drawoutline "true"
cl_crosshair_dynamic_maxdist_splitratio "0.3"
cl_crosshair_dynamic_splitalpha_innermod "1"
cl_crosshair_dynamic_splitalpha_outermod "0.5"
cl_crosshair_dynamic_splitdist "7"
cl_crosshair_outlinethickness "0.192549"
cl_crosshair_recoil "false"
cl_crosshair_sniper_width "1"
cl_crosshair_t "false"
cl_crosshairalpha "255"
cl_crosshaircolor "4"
cl_crosshaircolor_b "0"
cl_crosshaircolor_g "255"
cl_crosshaircolor_r "0"
cl_crosshairdot "false"
cl_crosshairgap "-2.598061"
cl_crosshairgap_useweaponvalue "false"
cl_crosshairsize "1.875223"
cl_crosshairstyle "4"
cl_crosshairthickness "0.1"
cl_crosshairusealpha "true"
cl_fixedcrosshairgap "3"
'@
$GameCfg['knife.cfg'] = @'
mp_drop_knife_enable true
subclass_create 508

echo Knife dropped
'@
$GameCfg['oceanvievv.cfg'] = @'
bind "mwheelup" "switchhands"
bind "mwheeldown" "+jump"

bind "scancode86" "volume 0.01"
bind "scancode87" "volume 0.25"

bind "scancode89" "buy vesthelm; buy vest"
bind "scancode90" "buy ak47; buy m4a1_silencer"
bind "scancode91" "buy defuser"
bind "scancode92" "buy awp"
bind "scancode93" "buy deagle"
bind "scancode94" "buy molotov; buy incgrenade"
bind "scancode95" "buy smokegrenade"
bind "scancode96" "buy flashbang"
bind "scancode97" "buy hegrenade"

bind "mouse4" "slot7"
bind "mouse5" "slot8"

bind "scancode65" "exec training"
bind "scancode66" "exec knife"

volume "0.1"
bind "scancode226" "+voicerecord"

bind "z" "radio1"
bind "x" "radio2"
bind "c" "radio3"

sensitivity "2.2"
zoom_sensitivity_ratio "1.0"

viewmodel_fov 68; 
viewmodel_offset_x 2.5
viewmodel_offset_y 0
viewmodel_offset_z -1.5
viewmodel_presetpos 3

echo Config loaded
'@
$GameCfg['training.cfg'] = @'
// General
bot_kick
mp_warmup_end
sv_cheats true
mp_limitteams 0
mp_autoteambalance 0

// Economy
mp_maxmoney 60000
mp_startmoney 60000
mp_buytime 9999
mp_buy_anywhere 1

// Round settings
mp_freezetime 0
mp_roundtime 60
mp_roundtime_defuse 60
mp_restartgame 1

// Respawn
mp_respawn_on_death_ct 1
mp_respawn_on_death_t 1

// Practice / visuals
sv_infinite_ammo 1
sv_showimpacts 1
sv_showimpacts_time 10
ammo_grenade_limit_total 5
sv_grenade_trajectory_prac_pipreview 1

// Binds
bind alt "noclip"
bind "CAPSLOCK" "sv_rethrow_last_grenade"
bind "MOUSE3" "ent_fire smokegrenade_projectile kill; ent_fire molotov_projectile kill; ent_fire flashbang_projectile kill; ent_fire hegrenade_projectile kill; ent_fire decoy_projectile kill; ent_fire inferno kill; stopsound"

echo Training mode activated
'@
$VideoCfg = [ordered]@{}
$VideoCfg['cs2_video.txt'] = @'
"video.cfg"
{
	"Version"		"16"
	"VendorID"		"4318"
	"DeviceID"		"7171"
	"setting.cpu_level"		"1"
	"setting.gpu_mem_level"		"3"
	"setting.gpu_level"		"3"
	"setting.knowndevice"		"1"
	"setting.defaultres"		"1440"
	"setting.defaultresheight"		"1080"
	"setting.refreshrate_numerator"		"144001"
	"setting.refreshrate_denominator"		"1000"
	"setting.fullscreen"		"1"
	"setting.coop_fullscreen"		"0"
	"setting.nowindowborder"		"1"
	"setting.mat_vsync"		"0"
	"setting.fullscreen_min_on_focus_loss"		"1"
	"setting.high_dpi"		"0"
	"Autoconfig"		"2"
	"setting.shaderquality"		"0"
	"setting.r_texturefilteringquality"		"0"
	"setting.msaa_samples"		"0"
	"setting.r_csgo_cmaa_enable"		"1"
	"setting.videocfg_shadow_quality"		"0"
	"setting.videocfg_dynamic_shadows"		"0"
	"setting.videocfg_texture_detail"		"0"
	"setting.videocfg_particle_detail"		"0"
	"setting.videocfg_ao_detail"		"0"
	"setting.videocfg_hdr_detail"		"3"
	"setting.videocfg_fsr_detail"		"4"
	"setting.monitor_index"		"0"
	"setting.r_low_latency"		"1"
	"setting.aspectratiomode"		"0"
}
'@
$CloudCfg = [ordered]@{}
$CloudCfg['cs2_user_convars_0_slot0.vcfg'] = @'
"config"
{
	"convars"
	{
		"cl_buymenu_ct_nextround_high"		"5000"
		"cl_buymenu_ct_nextround_low"		"1400"
		"cl_buymenu_t_nextround_high"		"5000"
		"cl_buymenu_t_nextround_low"		"1400"
		"cl_buywheel_donate_key"		"0"
		"cl_buywheel_nonumberpurchasing"		"false"
		"cl_crosshair_drawoutline"		"true"
		"cl_crosshair_dynamic_maxdist_splitratio"		"0.3"
		"cl_crosshair_dynamic_splitalpha_innermod"		"1"
		"cl_crosshair_dynamic_splitalpha_outermod"		"0.5"
		"cl_crosshair_dynamic_splitdist"		"7"
		"cl_crosshair_outlinethickness"		"0.192549"
		"cl_crosshair_recoil"		"false"
		"cl_crosshair_sniper_width"		"1"
		"cl_crosshair_t"		"false"
		"cl_crosshairalpha"		"255"
		"cl_crosshaircolor"		"4"
		"cl_crosshaircolor_b"		"0"
		"cl_crosshaircolor_g"		"255"
		"cl_crosshaircolor_r"		"0"
		"cl_crosshairdot"		"false"
		"cl_crosshairgap"		"-2.598061"
		"cl_crosshairgap_useweaponvalue"		"false"
		"cl_crosshairsize"		"1.875223"
		"cl_crosshairstyle"		"4"
		"cl_crosshairthickness"		"0.1"
		"cl_crosshairusealpha"		"true"
		"cl_debounce_zoom"		"true"
		"cl_fixedcrosshairgap"		"3"
		"cl_grenadecrosshair_decoy"		"true"
		"cl_grenadecrosshair_explosive"		"true"
		"cl_grenadecrosshair_fire"		"true"
		"cl_grenadecrosshair_flash"		"true"
		"cl_grenadecrosshair_keepusercrosshair"		"true"
		"cl_grenadecrosshair_smoke"		"true"
		"cl_grenadecrosshairdelay_decoy"		"2"
		"cl_grenadecrosshairdelay_explosive"		"2"
		"cl_grenadecrosshairdelay_fire"		"2"
		"cl_grenadecrosshairdelay_flash"		"2"
		"cl_grenadecrosshairdelay_smoke"		"2"
		"cl_inventory_radial_immediate_select"		"true"
		"cl_inventory_radial_tap_to_cycle"		"true"
		"cl_ironsight_dot_scale"		"1"
		"cl_ironsight_usecrosshaircolor"		"false"
		"cl_prefer_lefthanded"		"false"
		"cl_showloadout"		"true"
		"cl_silencer_mode"		"0"
		"cl_sniper_auto_rezoom"		"true"
		"cl_use_opens_buy_menu"		"false"
		"con_enable"		"true"
		"crosshair"		"true"
		"hud_showtargetid"		"true"
		"input_button_code_is_scan_code_scd"		"true"
		"joy_axisr_deadzone"		"0.15"
		"joy_axisr_relative"		"false"
		"joy_axisu_deadzone"		"0.15"
		"joy_axisu_relative"		"false"
		"joy_axisv_deadzone"		"0.15"
		"joy_axisv_relative"		"false"
		"joy_axisx_deadzone"		"0.15"
		"joy_axisx_relative"		"false"
		"joy_axisy_deadzone"		"0.15"
		"joy_axisy_relative"		"false"
		"joy_axisz_deadzone"		"0.15"
		"joy_axisz_relative"		"false"
		"joy_circle_correct_mode"		"1"
		"joy_circle_correct_mode_vehicle"		"2"
		"joy_forward_sensitivity"		"1"
		"joy_movement_stick"		"false"
		"joy_pitch_sensitivity"		"3"
		"joy_pitchsensitivity"		"1"
		"joy_response_look"		"0"
		"joy_response_move"		"9"
		"joy_side_sensitivity"		"1"
		"joy_yaw_sensitivity"		"3"
		"joy_yawsensitivity"		"-1"
		"m_pitch"		"0.022"
		"m_yaw"		"0.022"
		"name"		"oceanvievv"
		"option_duck_method"		"false"
		"option_speed_method"		"false"
		"player_nevershow_communityservermessage"		"1"
		"player_teamplayedlast"		"3"
		"sensitivity"		"2.2"
		"sensitivity_y_scale"		"1"
		"skill"		"1"
		"viewmodel_fov"		"68"
		"viewmodel_offset_x"		"2.5"
		"viewmodel_offset_y"		"0"
		"viewmodel_offset_z"		"-1.5"
		"voice_vox"		"0"
		"zoom_sensitivity_ratio"		"1"
	}
}
'@
$CloudCfg['cs2_user_keys_0_slot0.vcfg'] = @'
"config"
{
	"bindings"
	{
		"v"		"<unbound>"
		"KP_1"		"buy vesthelm; buy vest"
		"KP_2"		"buy ak47; buy m4a1_silencer"
		"KP_3"		"buy defuser"
		"KP_4"		"buy awp"
		"KP_5"		"buy deagle"
		"KP_6"		"buy molotov; buy incgrenade"
		"KP_7"		"buy smokegrenade"
		"KP_8"		"buy flashbang"
		"KP_9"		"buy hegrenade"
		"KP_MINUS"		"volume 0.01"
		"KP_PLUS"		"volume 0.25"
		"ALT"		"+voicerecord"
		"F7"		"exec oceanvievv"
		"F8"		"exec training"
		"F9"		"exec knife"
		"MOUSE4"		"slot7"
		"MOUSE5"		"slot8"
		"MWHEELUP"		"switchhands"
		"MWHEELDOWN"		"+jump"
		"c"		"radio3"
		"x"		"radio2"
		"`"		"toggleconsole"
		"ENTER"		"ent_fire_output script OnUser1 KeyInput,Enter"
		"BACKSPACE"		"ent_fire_output script OnUser1 KeyInput,Backspace"
		"DEL"		"mute"
		"MOUSE3"		"ent_fire smokegrenade_projectile kill; ent_fire molotov_projectile kill; ent_fire flashbang_projectile kill; ent_fire hegrenade_projectile kill; ent_fire decoy_projectile kill; ent_fire inferno kill; stopsound"
		"z"		"radio1"
		"i"		"demo_togglepause"
		"j"		"demo_goto -320 relative"
		"o"		"toggle spec_show_xray"
		"KP_MULTIPLY"		"demo_timescale 0.25"
		"MOUSE1"		"+attack"
		"TAB"		"+showscores"
		"0"		"slot10"
		"1"		"slot1"
		"2"		"slot2"
		"3"		"slot3"
		"4"		"slot4"
		"5"		"slot5"
		"6"		"slot6"
		"7"		"slot7"
		"8"		"slot8"
		"9"		"slot9"
		"a"		"+left"
		"b"		"buymenu"
		"d"		"+right"
		"e"		"+use"
		"f"		"+lookatweapon"
		"g"		"drop"
		"l"		"lefthand1"
		"m"		"teammenu"
		"n"		"noclip"
		"q"		"lastinv"
		"r"		"+reload"
		"s"		"+back"
		"u"		"messagemode2"
		"w"		"+forward"
		"y"		"messagemode"
		"["		"demo_timescale 1"
		"]"		"demo_timescale 10"
		"/"		"ent_fire smokegrenade_projectile kill"
		"SPACE"		"+jump"
		"ESCAPE"		"cancelselect"
		"PAUSE"		"pause"
		"SHIFT"		"+sprint"
		"CTRL"		"+duck"
		"UPARROW"		"demo_pause"
		"DOWNARROW"		"demo_resume"
		"F2"		"rebuy"
		"MOUSE2"		"+attack2"
		"CAPSLOCK"		"sv_rethrow_last_grenade"
	}
}
'@
$MachineCfg = [ordered]@{}
$MachineCfg['cs2_machine_convars.vcfg'] = @'
"config"
{
	"convars"
	{
		"cl_allow_animated_avatars"		"true"
		"cl_autohelp"		"true"
		"cl_color"		"3"
		"cl_crosshair_friendly_warning"		"0"
		"cl_deathcampanel_position_dynamic"		"1"
		"cl_disable_round_end_report"		"false"
		"cl_dm_buyrandomweapons"		"true"
		"cl_enable_party_voice"		"true"
		"cl_force_spec_hud_color_to_team$1"		"true"
		"cl_hide_avatar_images"		"0"
		"cl_hud_color"		"0"
		"cl_hud_radar_background_alpha"		"0.627"
		"cl_hud_radar_blur_background"		"true"
		"cl_hud_radar_map_additive"		"true"
		"cl_hud_radar_scale"		"0.903726"
		"cl_hud_telemetry_frametime_poor"		"100"
		"cl_hud_telemetry_frametime_show"		"1"
		"cl_hud_telemetry_net_detailed"		"0"
		"cl_hud_telemetry_net_misdelivery_poor"		"5"
		"cl_hud_telemetry_net_misdelivery_show"		"1"
		"cl_hud_telemetry_net_quality_graph_show"		"0"
		"cl_hud_telemetry_ping_poor"		"100"
		"cl_hud_telemetry_ping_show"		"1"
		"cl_hud_telemetry_serverrecvmargin_graph_show"		"0"
		"cl_mute_all_but_friends_and_party"		"0"
		"cl_mute_enemy_team"		"false"
		"cl_net_buffer_ticks"		"0"
		"cl_observed_bot_crosshair"		"2"
		"cl_ping_fade_deadzone"		"60"
		"cl_ping_fade_distance"		"300"
		"cl_player_ping_mute"		"0"
		"cl_predict_body_shot_fx"		"false"
		"cl_predict_head_shot_fx"		"false"
		"cl_predict_kill_ragdolls"		"false"
		"cl_quickinventory_filename"		"radial_quickinventory.txt"
		"cl_quickinventory_lastinv"		"true"
		"cl_quickinventory_line_update_speed"		"65"
		"cl_radar_always_centered"		"true"
		"cl_radar_icon_scale_min"		"0.6"
		"cl_radar_rotate"		"true"
		"cl_radar_scale"		"0.960615"
		"cl_radar_scale_alternate$2"		"0.963307"
		"cl_radar_scale_dynamic"		"false"
		"cl_radar_show_all_players_when_spectating"		"true"
		"cl_radar_square_always"		"true"
		"cl_radar_square_when_spectating"		"true"
		"cl_radar_square_with_scoreboard"		"false"
		"cl_radial_radio_tab_0_text_1"		"#Chatwheel_requestspend"
		"cl_radial_radio_tab_0_text_2"		"#Chatwheel_requestweapon"
		"cl_radial_radio_tab_0_text_3"		"#Chatwheel_bplan"
		"cl_radial_radio_tab_0_text_4"		"#Chatwheel_followingyou"
		"cl_radial_radio_tab_0_text_5"		"#Chatwheel_midplan"
		"cl_radial_radio_tab_0_text_6"		"#Chatwheel_followme"
		"cl_radial_radio_tab_0_text_7"		"#Chatwheel_aplan"
		"cl_radial_radio_tab_0_text_8"		"#Chatwheel_requestecoround"
		"cl_radial_radio_tab_1_text_1"		"#Chatwheel_enemyspotted"
		"cl_radial_radio_tab_1_text_2"		"#Chatwheel_needbackup"
		"cl_radial_radio_tab_1_text_3"		"#Chatwheel_bplan"
		"cl_radial_radio_tab_1_text_4"		"#Chatwheel_bombcarrierspotted"
		"cl_radial_radio_tab_1_text_5"		"#Chatwheel_multipleenemieshere"
		"cl_radial_radio_tab_1_text_6"		"#Chatwheel_sniperspotted"
		"cl_radial_radio_tab_1_text_7"		"#Chatwheel_aplan"
		"cl_radial_radio_tab_1_text_8"		"#Chatwheel_inposition"
		"cl_radial_radio_tab_2_text_1"		"#Chatwheel_affirmative"
		"cl_radial_radio_tab_2_text_2"		"#Chatwheel_negative"
		"cl_radial_radio_tab_2_text_3"		"#Chatwheel_compliment"
		"cl_radial_radio_tab_2_text_4"		"#Chatwheel_thanks"
		"cl_radial_radio_tab_2_text_5"		"#Chatwheel_cheer"
		"cl_radial_radio_tab_2_text_6"		"#Chatwheel_peptalk"
		"cl_radial_radio_tab_2_text_7"		"#Chatwheel_sorry"
		"cl_radial_radio_tab_2_text_8"		"#Chatwheel_sectorclear"
		"cl_radial_radio_tap_to_ping"		"true"
		"cl_radial_radio_version_reset"		"12"
		"cl_sanitize_player_names"		"false"
		"cl_scoreboard_mouse_enable_binding"		"+attack2"
		"cl_scoreboard_survivors_always_on"		"false"
		"cl_show_clan_in_death_notice"		"true"
		"cl_show_observer_crosshair"		"2"
		"cl_sniper_delay_unscope"		"false"
		"cl_sniper_show_inaccuracy"		"true"
		"cl_teamid_overhead_colors_show$2"		"true"
		"cl_teamid_overhead_fade_near_crosshair"		"0.5"
		"cl_teamid_overhead_mode$2"		"3"
		"cl_teammate_colors_show"		"1"
		"cl_timeout"		"30"
		"cl_use_last_selected_weapon_slot_position"		"false"
		"cl_versus_intro"		"true"
		"cl_weapon_selection_rarity_color"		"false"
		"closecaption"		"false"
		"csgo_map_preview_scale"		"4.274836"
		"dsp_volume"		"0.8"
		"fov_desired"		"75"
		"fps_max"		"0"
		"fps_max_ui$2"		"200"
		"hud_fastswitch"		"0"
		"hud_scaling$3"		"1"
		"mapoverview_icon_scale"		"1"
		"mouse_inverty"		"false"
		"r_drawtracers_firstperson"		"true"
		"r_fullscreen_gamma"		"2.2"
		"r_icon_image_cache_to_disk"		"true"
		"r_player_visibility_mode"		"1"
		"r_show_build_info"		"true"
		"r_spectator_flashbang_opacity"		"0.6"
		"rate"		"786432"
		"safezonex"		"1"
		"safezoney"		"1"
		"snd_autodetect_latency"		"true"
		"snd_deathcamera_volume$4"		"0.16"
		"snd_duckerattacktime"		"0.5"
		"snd_duckerreleasetime"		"2.5"
		"snd_duckerthreshold"		"0.15"
		"snd_ducktovolume"		"0.55"
		"snd_gain"		"1"
		"snd_gamevoicevolume"		"1"
		"snd_gamevolume"		"1"
		"snd_headphone_eq"		"0"
		"snd_mapobjective_volume$4"		"0.04"
		"snd_menumap_volume$4"		"1"
		"snd_menumusic_volume$4"		"0.04"
		"snd_mixahead"		"0.001"
		"snd_musicvolume$2"		"1"
		"snd_mute_losefocus"		"true"
		"snd_mute_mvp_music_live_players"		"false"
		"snd_mvp_volume$4"		"0.16"
		"snd_roundaction_volume$4"		"0"
		"snd_roundend_volume$4"		"0.16"
		"snd_roundstart_volume$4"		"0"
		"snd_spatialize_lerp"		"0"
		"snd_steamaudio_enable_perspective_correction"		"true"
		"snd_steamaudio_source_pathing_debug"		"false"
		"snd_surf_volume_inair"		"0.5"
		"snd_surf_volume_map"		"0.3"
		"snd_surf_volume_slide"		"0.5"
		"snd_tensecondwarning_volume$4"		"0.04"
		"snd_toolvolume"		"1"
		"snd_voipvolume"		"1"
		"speaker_config"		"-1"
		"spec_centerchasecam"		"false"
		"spec_replay_autostart"		"true"
		"spec_show_xray"		"1"
		"spec_usenumberkeys_nobinds"		"true"
		"sv_voiceenable"		"true"
		"viewmodel_presetpos"		"3"
		"voice_always_sample_mic$2"		"false"
		"voice_modenable"		"true"
		"voice_threshold$2"		"-120"
		"volume"		"0.25"
	}
}
'@

$PackName      = 'oceanvievv'
$LaunchOptions = '+fps_max 0 -forcenovsync -nojoy -novid +engine_low_latency_sleep_after_client_tick true -language english -w 1440 -h 1080 -fullscreen +exec autoexec'
$ToolUrl       = 'https://github.com/oceanvievv/cs2-config'

# No switch on the command line means somebody double-clicked the launcher, so ask. The
# menu lives here and not in the .cmd above it: this half already knows the display
# language, and cmd would need its own detection to say the same thing in Russian.
if (-not ($Video -or $Convars -or $Check -or $Undo)) {
    Write-Host ''
    Write-Host (L '  CS2 CONFIG' '  КОНФИГ CS2') -ForegroundColor Cyan
    Write-Host ''
    Write-Host (L '    [1]  Apply everything     configs, crosshair, resolution and quality' `
                  '    [1]  Применить всё        конфиги, прицел, разрешение и качество')
    Write-Host (L '    [2]  Apply configs only   the video settings of this PC stay as they are' `
                  '    [2]  Только конфиги       настройки видео этого ПК останутся как есть')
    Write-Host (L '    [3]  Check                show what differs, change nothing' `
                  '    [3]  Проверить            показать различия, ничего не менять')
    Write-Host (L '    [4]  Undo                 put this PC back the way you found it' `
                  '    [4]  Откатить             вернуть ПК в то состояние, в котором застал')
    Write-Host ''
    $pick = Read-Host (L '  Choose 1-4, or just press Enter for 1' `
                         '  Выбери 1-4 или просто нажми Enter для 1')
    # "$pick", not $pick: with no console to read from, Read-Host hands back null, and
    # calling .Trim() on that would end the run with a stack trace instead of a default.
    switch ("$pick".Trim()) {
        '2'     { }
        '3'     { $Check = $true }
        '4'     { $Undo  = $true }
        default { $Video = $true }
    }
}

Write-Host ''
Write-Host (('=== ' + (L 'CS2 settings' 'Конфиг CS2') + ": $PackName ").PadRight(60, '=')) -ForegroundColor Cyan

$steam = Get-SteamPath
if (-not $steam) { Die 'Steam not found in the registry. Is Steam installed?' `
                       'Steam не найден в реестре. Он вообще установлен?' }
$cfgDir = Get-CS2CfgPath $steam
if (-not $cfgDir) { Die 'CS2 not found in any Steam library. Install CS2 first.' `
                        'CS2 не найдена ни в одной библиотеке Steam. Сначала установи игру.' }
$userCfg = Get-UserCfgPath $steam
Ok ((L 'CS2 cfg folder' 'Папка cfg').PadRight(17) + $cfgDir)

# --- undo -------------------------------------------------------------------------
if ($Undo) {
    if (-not (Test-Path $BackupRoot)) { Die 'No backup found on this PC. Nothing to undo.' `
                                            'На этом ПК нет резервной копии. Откатывать нечего.' }
    $last = Get-ChildItem $BackupRoot -Directory | Sort-Object Name -Descending | Select-Object -First 1
    if (-not $last) { Die 'No backup found on this PC. Nothing to undo.' `
                          'На этом ПК нет резервной копии. Откатывать нечего.' }
    Write-Host ''
    Write-Host (L "Restoring the files this PC had before, from $($last.Name)" `
                  "Возвращаю файлы, которые были на этом ПК, из копии $($last.Name)")
    $map = @{ 'cfg' = $cfgDir; 'video' = $userCfg; 'cloud' = $userCfg; 'machine' = $userCfg }
    foreach ($tag in $map.Keys) {
        $dir = Join-Path $last.FullName $tag
        if (-not (Test-Path $dir) -or -not $map[$tag]) { continue }
        foreach ($f in Get-ChildItem $dir -File) {
            if ($f.Name -eq '_added.txt') { continue }
            Copy-Item $f.FullName (Join-Path $map[$tag] $f.Name) -Force
            Info "$(Mark 'restored' 'возвращён')$tag/$($f.Name)"
        }
        $addedList = Join-Path $dir '_added.txt'
        if (Test-Path $addedList) {
            foreach ($n in (Get-Content $addedList)) {
                if ($n.Trim() -eq '') { continue }
                $victim = Join-Path $map[$tag] $n
                if (Test-Path $victim) { Remove-Item $victim -Force; Info "$(Mark 'removed' 'удалён')$tag/$n" }
            }
        }
    }
    Ok 'Undo complete. This PC is back to how you found it.' `
       'Откат выполнен. ПК в том состоянии, в котором ты его застал.'
    exit 0
}

# --- check ------------------------------------------------------------------------
if ($Check) {
    Write-Host ''
    Write-Host (L 'Comparing this pack against the PC (nothing will be written):' `
                  'Сравниваю набор с тем, что на ПК (ничего не записывается):')
    Compare-Payload $GameCfg  $cfgDir  'cfg'
    if ($userCfg) {
        Compare-Payload $VideoCfg   $userCfg 'video'
        Compare-Payload $MachineCfg $userCfg 'machine'
        Compare-Payload $CloudCfg   $userCfg 'cloud'
    }
    Write-Host ''
    Info 'Run without -Check to apply.' 'Запусти без -Check, чтобы применить.'
    exit 0
}

# --- apply ------------------------------------------------------------------------
Write-Host ''
Write-Host (L 'Writing configs:' 'Пишу конфиги:')
Write-Payload $GameCfg $cfgDir 'cfg'
Ok 'Configs in place. Crosshair included, no share code needed.' `
   'Конфиги на месте. Прицел внутри, код обмена не нужен.'

# Radar, fov, volumes, HUD scale. Steam Cloud does not carry these, so on any PC but the
# one they came from they are that machine's defaults unless this writes them. Applied
# with the configs rather than behind -Convars: nothing here belongs to Steam, so nothing
# overwrites it on the way out - only CS2 itself does, which is why it has to be closed.
if ($userCfg -and $MachineCfg.Count -gt 0) {
    Write-Host ''
    Write-Host (L 'Writing the settings Steam Cloud does not carry:' `
                  'Пишу настройки, которые не возит Steam Cloud:')
    Write-Payload $MachineCfg $userCfg 'machine'
    Warn 'CS2 must be closed for these: it rewrites this file when it exits.' `
         'Для них CS2 должна быть закрыта: при выходе она перезаписывает этот файл.'
}

if ($Video) {
    if (-not $userCfg) { Warn 'No CS2 userdata folder. Log into Steam, run CS2 once, retry.' `
                              'Нет папки userdata для CS2. Войди в Steam, запусти игру один раз и повтори.' }
    elseif ($VideoCfg.Count -eq 0) { Warn 'This pack has no video settings.' `
                                          'В этом наборе нет настроек видео.' }
    else {
        Write-Host ''
        Write-Host (L 'Writing video settings:' 'Пишу настройки видео:')
        Write-Payload $VideoCfg $userCfg 'video'
        Warn 'On a different GPU, CS2 re-detects and overrides some of this. The resolution is in the launch options for that reason.' `
             'На другой видеокарте CS2 определит её заново и часть этого перепишет. Поэтому разрешение продублировано в параметрах запуска.'
    }
} else {
    Info ''
    Info 'Video settings not touched. Pass -Video to apply them.' `
         'Настройки видео не тронуты. Передай -Video, чтобы применить и их.'
}

if ($Convars) {
    if (-not $userCfg) { Warn 'No CS2 userdata folder. Cannot restore the cloud backup.' `
                              'Нет папки userdata для CS2. Вернуть копию из облака не получится.' }
    else {
        Write-Host ''
        Write-Host (L 'Restoring Steam Cloud settings:' 'Возвращаю настройки из Steam Cloud:')
        Warn 'Close CS2 AND Steam first, or Steam overwrites these when it exits.' `
             'Сначала закрой и CS2, и Steam: иначе Steam перезапишет их при выходе.'
        Write-Payload $CloudCfg $userCfg 'cloud'
    }
}

if (Test-Path $Backup) {
    Write-Host ''
    Info "$(L 'Original files of this PC' 'Исходные файлы этого ПК'): $Backup"
    Info 'Run with -Undo to put them back.' 'Запусти с -Undo, чтобы вернуть их на место.'
}

Write-Host ''
Write-Host ((L '=== BY HAND ' '=== ВРУЧНУЮ ').PadRight(60, '=')) -ForegroundColor Cyan
if ($LaunchOptions -ne '') {
    Write-Host ''
    Write-Host (L 'Launch options (Steam > CS2 > Properties > General):' `
                  'Параметры запуска (Steam > CS2 > Свойства > Общие):') -ForegroundColor White
    Write-Host ''
    Write-Host "   $LaunchOptions" -ForegroundColor Yellow
    try {
        Set-Clipboard -Value $LaunchOptions
        Write-Host ''
        Info 'Copied to your clipboard. Just paste.' 'Скопировано в буфер обмена. Просто вставь.'
    } catch { }
}
Write-Host ''
Write-Host (L 'If you play a stretched 4:3 resolution, set GPU scaling too:' `
              'Если играешь в растянутом 4:3, настрой ещё и масштабирование:') -ForegroundColor White
Write-Host (L 'NVIDIA Control Panel > Adjust desktop size and position > Full-screen,' `
              'Панель управления NVIDIA > Регулировка размера и положения > Во весь экран,') -ForegroundColor White
Write-Host (L 'scaling on GPU, tick Override the scaling mode set by games.' `
              'масштабирование на GPU, галочка «Замещение режима масштабирования, заданного играми».') -ForegroundColor White
Write-Host ''
Write-Host (L 'Then start CS2 and check your crosshair, sensitivity and binds.' `
              'Дальше запусти CS2 и проверь прицел, чувствительность и бинды.') -ForegroundColor White
Write-Host ''
Write-Host (L "Made with cs2-config: $ToolUrl" "Собрано утилитой cs2-config: $ToolUrl") -ForegroundColor DarkGray
Write-Host ''